export const endpointManifest = [
  'POST /api/auth/send-otp',
  'POST /api/auth/verify-otp',
  'POST /api/auth/register',
  'POST /api/auth/login',
  'POST /api/auth/logout',
  'GET /api/auth/me',
  'POST /api/auth/forgot-password-init',
  'POST /api/auth/reset-password',
  'GET /api/auth/owner-info/:ownerId',
  'GET /api/users/:id/profile',
  'PUT /api/users/:id/profile',
  'POST /api/contact/send',
  'POST /api/reports/submit',
  'POST /api/consents/save',
  'GET /api/consents/check/:userId',
  'POST /favourites/save',
  'DELETE /favourites/remove',
  'GET /favourites/user/:userId',
  'GET /listings/all',
  'GET /listings/search',
  'GET /listings/searchWithFilters',
  'GET /listings/allWithFilters',
  'GET /listings/recent',
  'GET /listings/featured',
  'GET /listings/exploreCity',
  'POST /listings/add',
  'PUT /listings/update/:id',
  'DELETE /listings/delete/:id',
  'GET /listings/owner/:ownerId',
  'PATCH /listings/:id/status',
  'GET /listings/:id',
  'GET /listings/:id/reviews',
  'POST /listings/:id/reviews',
  'POST /activity/log',
  'GET /activity/analytics/most-viewed',
  'GET /activity/analytics/most-contacted',
  'GET /activity/analytics/most-shared',
  'GET /activity/analytics/top-areas',
  'GET /activity/analytics/summary',
  'GET /activity/analytics/recent',
  'GET /activity/analytics/owner/:ownerId',
  'GET /activity/analytics/property/:propertyId',
  'GET /activity/user/:userId',
  'GET /activity/user/:userId/insights',
  'GET /api/flatmates',
  'POST /api/flatmates',
  'GET /api/flatmates/memory-feed',
  'GET /api/flatmates/nearby',
  'GET /api/flatmates/check-status',
  'DELETE /api/flatmates/:postId',
  'GET /api/messages/conversations/:userId',
  'GET /api/messages/history',
  'PUT /api/messages/conversations/:conversationId/accept',
] as const;

export const websocketManifest = {
  endpoint: '/ws-chat',
  appDestinations: [
    '/app/chat.connect',
    '/app/chat.send',
    '/app/chat.read',
    '/app/chat.typing',
    '/app/chat.disconnect',
  ],
  userTopicPattern: '/topic/messages.{userId}',
  onlineTopic: '/topic/users.online',
} as const;
